language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-request-tracker.gemspec
- gem install sensu-plugins-request-tracker-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: h/nl5rLtZopJbi7khsDZd/oc/nYKKZ33MI2SNDtz5Cjp9wAWdkbPy539iuCTqLrhZqEYvy3fkT5/UEfBsSE4OaHvaJ4/Dx0u1sM8mBm+GzurpEN2wguCpATO4ilmuAVP7bVk7JGPBzckQMdR7PuPyFwL69f+K49zE9SaLm+cq+M=
  gem: sensu-plugins-request-tracker
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-request-tracker
